### ISSUE TITLE
Using your Libraries with Seed Studio Tft Touchshiel Version2

### ISSUE THREAD

**Issue by AvasDream** [rsk22/Arduino-TouchScreen-Buttons#1]
Hello, first of all nice work! 
I bought a Tft Touchshield 2.8" and this requires the TFT_Touch_Shield_V2 Library. Is there a way to use your libraries with the seconde Version? Or just a quick hint how to make them compatible? 
Thank you for the help and best regards :)

**Comment by rsk22** [comment]
Hey, Avas.  Thanks for the compliment!

When I wrote this code, I do not believe the Version 1 was released at this time.  The API was changed when they went to 2.0 so there would be minor refactoring (i.e. calls to library names).  

I am not sure if you have a familiarity with Object Oriented Programming but this should be relatively easy to update since it is very modular.  Would you prefer to branch this or would you like for me to make an update?  If I make an update, I could finish this in a week or two, but I would need to buy the new SeeedStudio 2.0 touch screen.  This could be the excuse I have been looking for to get back on my Arduino projects and update these libraries.

**Comment by AvasDream** [comment]
Thank you for the fast reply! I finished the Project by using the default library but thank you for your help :)
